package edu.neu.coe.huskySort.util;

import java.time.LocalDateTime;
import java.util.function.Consumer;
import java.util.function.Supplier;

/**
 * Class to implement an annotated aggregator.
 * In an annotated aggregator, the run method invokes the run method of the underlying aggregator, but takes the result and formats it appropriately, sending the resulting String to the annotator.
 * The run method itself returns void.
 *
 * @param <T> the underlying type of the Aggregator.
 */
public class AnnotatedAggregator<T> {

    /**
     * Constructor.
     *
     * @param annotator      this is the Consumer&lt;String&gt; which accepts the preamble and the colophon Strings generated by the run method.
     * @param preambleFormat this is the format string which will, as part of the run method, generate a String to be sent to the annotator immediately before invoking run on the aggregator;
     *                       NOTE: this format string must include a %t (datetime format) directive to format the current date/time (see documentation on String.format).
     * @param aggregator     this is the aggregator instance which will be used to implement the run method.
     * @param colophonFormat this is the format string which will, as part of the run method, generate a String to be sent to the annotator immediately after invoking run on the aggregator;
     *                       NOTE: this format string must include a %f (floating format) directive to format the result of renderer function (see documentation on String.format).
     */
    public AnnotatedAggregator(Consumer<String> annotator, String preambleFormat, Aggregator<T> aggregator, String colophonFormat) {
        this.aggregator = aggregator;
        this.annotator = annotator;
        this.preambleFormat = preambleFormat;
        this.colophonFormat = colophonFormat;
    }

    /**
     * Method to run the aggregator, given a specific T value.
     *
     * @param t the value of T
     * @param m the number of runs
     */
    public void run(T t, int m, Supplier<Double> aggregate) {
        // CONSIDER whether this is actually inefficient
        run(() -> t, m, aggregate);
    }

    /**
     * Method to run the aggregator, given a supplier of T values.
     *
     * @param supplier the supplier
     * @param m        the number of runs
     */
    public void run(Supplier<T> supplier, int m, Supplier<Double> aggregate) {
        annotator.accept(String.format(preambleFormat, LocalDateTime.now()));
        aggregator.run(supplier, m);
        if (colophonFormat != null) annotator.accept(String.format(colophonFormat, aggregate.get()));
    }

    private final Consumer<String> annotator;
    private final String preambleFormat;
    private final String colophonFormat;
    private final Aggregator<T> aggregator;

}
