package edu.neu.coe.huskySort.sort.huskySortUtils;

import net.sourceforge.pinyin4j.PinyinHelper;
import org.junit.Test;

import java.util.Arrays;
import java.util.Map;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

/**
 * Tests for the corpus-trained polyphone override table (TODO.md item 11): the
 * {@code polyphone_overrides.txt} resource generated by {@link PolyphoneOverrideTrainer}, its
 * loader in {@link ChineseCharacter}, and the override lookup in {@code ChineseCharacter.alt()}.
 */
public class PolyphoneOverrideTest {

    /**
     * (i) An overridden character returns the override reading via alt(). 肖 is in the trained
     * table: pinyin4j's default reading is xiao4, but as a surname (its dominant use in a
     * names corpus) it reads xiao1, which is what the corpus curator's ordering shows -- the
     * trainer found 22 discriminating pairs FOR xiao1, 0 against.
     */
    @Test
    public void testOverriddenCharacterUsesTrainedReading() {
        // Confirm the premise: xiao4 is pinyin4j's default (element 0), so without the
        // override this would return "xiao 4".
        final String[] readings = PinyinHelper.toHanyuPinyinStringArray('肖');
        assertEquals("xiao4", readings[0]);
        assertEquals("xiao 1", new ChineseCharacter('肖').alt());
    }

    /**
     * (ii) A non-polyphone character's alt() output is unchanged by the override machinery
     * (卞 has the single reading bian4; same expectation as ChineseCharacterTest.testAlt).
     */
    @Test
    public void testNonPolyphoneCharacterUnchanged() {
        assertEquals("bian 4", new ChineseCharacter('卞').alt());
        assertEquals("bi 4", new ChineseCharacter('毕').alt());
    }

    /**
     * (iii) A polyphone character NOT in the table still falls back to pinyinStrings[0].
     * 何 (he2/he4) is a genuine polyphone but earned no override (the corpus is consistent
     * with pinyin4j's default he2), so alt() must keep returning the default.
     */
    @Test
    public void testPolyphoneAbsentFromTableFallsBackToDefault() {
        final String[] readings = PinyinHelper.toHanyuPinyinStringArray('何');
        assertTrue("premise: 何 is a polyphone", Arrays.stream(readings).distinct().count() >= 2);
        assertFalse("premise: 何 is not in the trained table", ChineseCharacter.loadPolyphoneOverrides().containsKey('何'));
        assertEquals("he " + readings[0].charAt(readings[0].length() - 1), new ChineseCharacter('何').alt());
        assertEquals("he 2", new ChineseCharacter('何').alt());
    }

    /**
     * (iv) The loader tolerates the resource being present and well-formed: the table is
     * non-empty, and every entry is coherent -- single-character key, a reading that pinyin4j
     * actually reports as valid for that character (alt()'s precondition for honoring an
     * override), and alt() actually reflecting it end-to-end.
     */
    @Test
    public void testLoaderReadsShippedResource() {
        final Map<Character, String> table = ChineseCharacter.loadPolyphoneOverrides();
        assertNotNull(table);
        assertTrue("trained table should be non-empty", table.size() > 0);
        assertEquals("xiao1", table.get('肖'));
        for (final Map.Entry<Character, String> entry : table.entrySet()) {
            final char c = entry.getKey();
            final String reading = entry.getValue();
            final String[] readings = PinyinHelper.toHanyuPinyinStringArray(c);
            assertNotNull("override for a character with no pinyin: " + c, readings);
            assertTrue("override '" + reading + "' is not a valid pinyin4j reading of " + c,
                    Arrays.asList(readings).contains(reading));
            // End-to-end: alt() must render exactly this reading (post-processed).
            assertEquals("alt() should reflect the override for " + c,
                    ChineseCharacter.toAltFormat(reading), new ChineseCharacter(c).alt());
        }
    }
}
